### ISSUE TITLE
*.g.dart files are missing

### ISSUE THREAD

**Issue by wonderful89** [fadhilx/json_to_model#1]
## evn
```
Flutter 1.12.13+hotfix.6 • channel unknown • unknown source
Framework • revision 18cd7a3601 (3 months ago) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```
## config

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_to_model: ^1.3.9
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
```
## command 

flutter packages pub run json_to_model

## result
![image](https://user-images.githubusercontent.com/44089389/75869605-c4288b80-5e44-11ea-8051-7ef7022c0c22.png)

I can not generate the *.g.dart files.
